### PR TITLE
Print error msg to stderr if starting in an non wayland session

### LINKED ISSUE #6: proper error handling on non wayland sessions
if executed on xorg, instead of:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoCompositor', src/main.rs:100:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

just tell the user that only wayland is supported

### PR DESCRIPTION
**Pull request by 6543**
close  #6

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -97,7 +97,13 @@ fn main() {
 }
 
 fn gui(args: &Args) -> Option<(DynamicImage, Rect)> {
-    let conn = Connection::connect_to_env().unwrap();
+    let conn = Connection::connect_to_env();
+    if conn.is_err() {
+        eprintln!("Could not connect to the Wayland server, make sure you run watershot within a Wayland session!");
```
Comment (Kirottu) [inline src/main.rs:102]: `env_logger` is used, so `log::error!` should be used to print out errors.

**Comment by 6543** [comment]
@Kirottu changed
